### ISSUE TITLE
Documentation has incorrect repo name

### ISSUE THREAD

**Issue by zdk123** [tryfabric/notion-github-action#65]
### Describe the bug

Action errors out with `Unable to resolve actions. Repository not found`

### Steps to reproduce

Create a workflow with the following job run details:

```yml
jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: Add GitHub Issues to Notion
    steps:
      - name: Add GitHub Issues to Notion
        uses: instantish/notion-github-action@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
```

### Expected behavior

A completed action.

### Additional context

It appears that github actions cannot resolve redirects: https://github.com/orgs/community/discussions/25727

It looks like the documentation should be updated to reflect the actual (updated?) org name.

thank you!
